#!/usr/bin/env python3

import sys
import os

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QIcon

from widgets.launcher import LauncherWindow

if __name__ == '__main__':
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

    launch_file = ''
    try:
        launch_file = sys.argv[1]
        print("[INFO] app start with open", launch_file)
    except:
        print("[INFO] app start")

    app = QApplication(sys.argv)
    with open(SCRIPT_DIR + '/ui/stylesheet.css', 'r') as f:
        style = f.read()
        app.setStyleSheet(style)

    ui_main = LauncherWindow(SCRIPT_DIR + '/ui/launcher.ui')
    ui_main.setWindowIcon(QIcon(SCRIPT_DIR + '/img/ros_launcher.png'))
    ui_main.show()

    if launch_file != '':
        ui_main.set_launch_file(launch_file)
        
    sys.exit(app.exec())
